Repository arkadiko-dao/arkadiko, pull requests merged in 2021-06, with the labels that each got.

#13 Remove appearance of input type number in Firefox
  web/components/swap.tsx
Labels: enhancement

#15 Clean up testnet modal UI
  web/components/testnet-modal.tsx
Labels: enhancement

#20 Mint: UI improvements
  web/components/collateral-type-group.tsx
  web/components/collateral-type.tsx
  web/components/home.tsx
  web/components/mint.tsx
  web/components/swap.tsx
  web/public/assets/tokens/diko.png
  web/public/assets/tokens/stx.png
  web/public/assets/tokens/xusd.png
Labels: enhancement

#23 Navigation refactoring
  web/components/collateral-type-group.tsx
  web/components/collateral-type.tsx
  web/components/header.tsx
  web/components/home.tsx
Labels: enhancement

#45 Navigation fixes
  web/components/header.tsx
Labels: enhancement

#77 Make navbar sticky
  web/components/header.tsx
Labels: important improvement

#79 Add `Max.` button on input fields where you can enter an amount
  web/components/app.tsx
  web/components/create-vault-step-one.tsx
  web/components/header.tsx
  web/components/input-amount.tsx
  web/components/manage-vault.tsx
  web/components/stake.tsx
Labels: important improvement

#87 Vault creation UX/UI improvements
  web/components/collateral-type-group.tsx
  web/components/create-vault-confirm.tsx
  web/components/create-vault-step-one.tsx
  web/components/input-amount.tsx
Labels: nice to have

#96 Add information in tooltips for Swap section
  web/components/swap-settings.tsx
  web/components/swap.tsx
Labels: nice to have

#94 fix: add stxAddress to all contract calls to sign from the correct address
  web/components/add-swap-liquidity.tsx
  web/components/auction-group.tsx
  web/components/auctions.tsx
  web/components/create-vault-transact.tsx
  web/components/lot.tsx
  web/components/manage-vault.tsx
  web/components/mint.tsx
  web/components/remove-swap-liquidity.tsx
  web/components/stake.tsx
  web/components/swap.tsx
  web/components/vault.tsx
  web/components/view-proposal.tsx
Labels: bug

#102 Better UX for Swap button
  web/components/swap.tsx
Labels: important improvement

#105 Swap: fixes overflow and broken layout when input is too long
  web/components/swap.tsx
Labels: nice to have
